# Generated by adevtool; do not edit
# For more info, see https://github.com/kdrag0n/adevtool

BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

AB_OTA_PARTITIONS += \
    vbmeta_system \
    vendor \
    vendor_dlkm

TARGET_BOARD_INFO_FILE := vendor/google_devices/raven/firmware/android-info.txt

BOARD_VENDOR_SEPOLICY_DIRS += \
    hardware/google/pixel-sepolicy/input \
    device/google/gs101-sepolicy/whitechapel/vendor/google/exo_camera_injection \
    hardware/google/pixel-sepolicy/connectivity_thermal_power_manager \
    device/google/gs101-sepolicy/ambient
